### ISSUE TITLE
Can't install UWP - Certificate Error

### ISSUE THREAD

**Issue by mica** [Xonshiz/CoManga#1]
When I attempt to install the app on Windows 10, I get: 

> Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

**Comment by Xonshiz** [comment]
Somehow I knew I'll be getting this one. I'm out of town for 2 days, I'll take a look at this on Monday.

**Comment by Xonshiz** [comment]
@mica I've updated the UWP package. Can you please download that UWP.CoManga.zip file and try installing CoManga by double clicking on "comic_dl.UWP_1.0.0.0_x86_x64_arm.appxbundle".

**Comment by sergiotapia** [comment]
Same error:

```
Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)
```

**Comment by Xonshiz** [comment]
Yep, this is an issue with the certificate. Since it's a self signed certificate, I need to look into how to update it to get it working.

**Comment by nanny07** [comment]
The UWP installer will not install the certificate nor the dependencies packages

You have to install it manually and put in on the local machine under the Trusted Root Authorities section.
For future reference, here a link: https://blogs.msdn.microsoft.com/appinstaller/2016/05/27/app-installer/

**Comment by Xonshiz** [comment]
You dn't need to install CoManga from this .zip file. You can fetch the updated binary from the Microsoft Windows Store directly now.

Get It Here : [CoManga UWP](https://www.microsoft.com/en-us/p/comanga/9n81f8b5ww93)

Please do confirm so I can close this.

**Comment by Xonshiz** [comment]
Will be closing this now.

**Comment by dwaaad** [comment]
> You don't need to install CoManga from this .zip file. You can fetch the updated binary from the Microsoft Windows Store directly now.
> 
> Get It Here : [CoManga UWP](https://www.microsoft.com/en-us/p/comanga/9n81f8b5ww93)
> 
> Please do confirm so I can close this.

This solution no longer works

**Comment by dwaaad** [comment]
> You don't need to install CoManga from this .zip file. You can fetch the updated binary from the Microsoft Windows Store directly now.
> 
> Get It Here : [CoManga UWP](https://www.microsoft.com/en-us/p/comanga/9n81f8b5ww93)
> 
> Please do confirm so I can close this.

This link no longer works
