### ISSUE TITLE
readcomicsonline.me has a new domain name, causing CoManga comic search to fail

### ISSUE THREAD

**Issue by cooltwa** [Xonshiz/CoManga#3]
Getting the error "Dead. Exception occurred. Please try again after some time" when clicking the Comics tab (Windows Store version). If you go to https://readcomicsonline.me/ they have a message up saying to use their new domain https://comicpunch.net/.

**Comment by Xonshiz** [comment]
Thanks a ton for informing me about this. I went to the old site, but didn't get any message. But, comicpunch seems to be the same. Will update the code accordingly and push the changes soon.

**Comment by Xonshiz** [comment]
I've pushed the update for this and it's working. Please fetch the latest binaries.
