### ISSUE TITLE
[Android App] Exception Occured. Please try again after some time.

### ISSUE THREAD

**Issue by junevm** [Xonshiz/CoManga#9]
Getting exception occured error when opening CoManga android app. Please fix this fast.

**Comment by Xonshiz** [comment]
Refer to #8 

EDIT: Fixed Issue Id

**Comment by junevm** [comment]
Where,what #28?

**Comment by junevm** [comment]
> Refer to #28
> 
What is #28?

**Comment by Xonshiz** [comment]
Updated the Issue Id. Please refer to that convo itself.
